const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const src=fs.readFileSync('ส่งงาน/gradebook.js','utf8').split('/* BEGIN GRADEBOOK SYNC')[1].split('/* END GRADEBOOK SYNC */')[0];
const code='/* BEGIN GRADEBOOK SYNC'+src;
function setup(request){
 const storage=new Map(),timers=[],messages=[],nodes={retrySave:{hidden:true}};
 const ctx={DB:{sets:{room:{data:{student:{exam:4}}}}},activeWorkspace:'A',unlocked:true,cloudBusy:false,pendingPush:false,pushTimer:null,Date,JSON,Number,Promise,Error,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},sessionStorage:{getItem:()=>''},document:{getElementById:id=>nodes[id]},cloudUrl:()=>'/mock',setStatus:m=>messages.push(m),afterDataReady:()=>{},promptUnlock:()=>{},KNTNetwork:{json:request},setTimeout:fn=>{timers.push(fn);return timers.length},clearTimeout:()=>{}};
 vm.createContext(ctx);vm.runInContext(code,ctx);return {ctx,storage,timers,messages};
}
test('refresh never overwrites an existing unsent draft',async()=>{let calls=0;const {ctx}=setup(async()=>{calls++;return {ok:true,data:{sets:{}}}});ctx.save();await ctx.refreshFromCloud();assert.equal(calls,0);assert.equal(ctx.DB.sets.room.data.student.exam,4);});
test('editing during a slow read wins over the late server response',async()=>{let resolve;const {ctx}=setup(()=>new Promise(r=>resolve=r));const pending=ctx.refreshFromCloud();ctx.DB.sets.room.data.student.exam=9;ctx.save();resolve({ok:true,data:{sets:{}}});await pending;assert.equal(ctx.DB.sets.room.data.student.exam,9);assert.equal(ctx.localDirty,true);});
test('late reads cannot overwrite a different teacher workspace',async()=>{let resolve;const {ctx}=setup(()=>new Promise(r=>resolve=r));const pending=ctx.refreshFromCloud();ctx.activeWorkspace='B';ctx.DB={sets:{other:{}}};resolve({ok:true,data:{sets:{wrong:{}}}});await pending;assert(ctx.DB.sets.other);});
test('successful older write leaves newer scores marked dirty',async()=>{let resolve,sent;const {ctx}=setup((url,options)=>{sent=JSON.parse(options.body);return new Promise(r=>resolve=r)});ctx.save();const pending=ctx.pushNow();ctx.DB.sets.room.data.student.exam=8;ctx.save();resolve({ok:true});await pending;assert.equal(sent.data.sets.room.data.student.exam,4);assert.equal(ctx.DB.sets.room.data.student.exam,8);assert.equal(ctx.localDirty,true);});
test('uncertain writes pause instead of retrying automatically',async()=>{let calls=0;const {ctx}=setup(async()=>{calls++;throw new Error('timeout')});ctx.save();await ctx.pushNow();await ctx.pushNow();assert.equal(calls,1);assert.equal(ctx.syncPaused,true);assert.equal(ctx.localDirty,true);});
test('reload restores unsent data and does not automatically send it',()=>{let calls=0;const {ctx}=setup(()=>{calls++});ctx.save();ctx.localDirty=false;ctx.load();assert.equal(ctx.localDirty,true);assert.equal(ctx.syncPaused,true);assert.equal(calls,0);});
test('successful acknowledgement clears only its own draft revision',async()=>{const {ctx,storage}=setup(async()=>({ok:true}));ctx.save();await ctx.pushNow();assert.equal(ctx.localDirty,false);assert.equal(JSON.parse(storage.get('hwSyncState_A')).dirty,false);});
test('replacing cached cloud data keeps the previous data recoverable',()=>{const {ctx,storage}=setup(()=>{});ctx.persistDraft();ctx.backupBeforeReplace('A',{sets:{new:{}}});assert.equal(JSON.parse(storage.get('hwRecovery_A'))[0].data.sets.room.data.student.exam,4);});
